# DATA PRE PROCESSING/DATA PREPARATION

* Data cleaning - drop,fillna with mean, median, mode imputation, changing dtypes
* Data Transformation
* If data is continuous - Standard scaler, minmaxscaler,Robustscaler
* If data is Discrete - Label encoder, one hot encoder

# Import Neccessary Libraries

In [1]:
import pandas as pd

# Import Dataset

In [50]:
weather_data = pd.read_csv("environmental_data.csv")
weather_data

     Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0             1   41.0    190.0   7.4     67     5    1  2010    67       S
1             2   36.0    118.0   8.0     72     5    2  2010    72       C
2             3   12.0    149.0  12.6     74     5    3  2010    74      PS
3             4   18.0    313.0  11.5     62     5    4  2010    62       S
4             5    NaN      NaN  14.3     56     5    5  2010    56       S
..          ...    ...      ...   ...    ...   ...  ...   ...   ...     ...
153         154   41.0    190.0   7.4     67     5    1  2010    67       C
154         155   30.0    193.0   6.9     70     9   26  2010    70      PS
155         156    NaN    145.0  13.2     77     9   27  2010    77       S
156         157   14.0    191.0  14.3     75     9   28  2010    75       S
157         158   18.0    131.0   8.0     76     9   29  2010    76       C

[158 rows x 10 columns]

# Data Understanding

In [51]:
weather_data.dtypes

Unnamed: 0      int64
Ozone         float64
Solar.R       float64
Wind          float64
Temp C         object
Month          object
Day             int64
Year            int64
Temp            int64
Weather        object
dtype: object

In [52]:
weather_data.shape

(158, 10)

In [53]:
weather_data.isna().sum()

Unnamed: 0     0
Ozone         38
Solar.R        7
Wind           0
Temp C         0
Month          0
Day            0
Year           0
Temp           0
Weather        3
dtype: int64

In [54]:
weather_data.describe(include="all")

,Unnamed: 0,Ozone,Solar.R,Wind,Temp C,Month,Day,Year,Temp,Weather
count,158.000000,120.000000,151.000000,158.000000,158,158,158.000000,158.0,158.000000,155
unique,NaN,NaN,NaN,NaN,41,6,NaN,NaN,NaN,3
top,NaN,NaN,NaN,NaN,81,9,NaN,NaN,NaN,S
freq,NaN,NaN,NaN,NaN,11,34,NaN,NaN,NaN,59
mean,79.500000,41.583333,185.403974,9.957595,NaN,NaN,16.006329,2010.0,77.727848,NaN
std,45.754781,32.620709,88.723103,3.511261,NaN,NaN,8.997166,0.0,9.377877,NaN
min,1.000000,1.000000,7.000000,1.700000,NaN,NaN,1.000000,2010.0,56.000000,NaN
25%,40.250000,18.000000,119.000000,7.400000,NaN,NaN,8.000000,2010.0,72.000000,NaN
50%,79.500000,30.500000,197.000000,9.700000,NaN,NaN,16.000000,2010.0,78.500000,NaN
75%,118.750000,61.500000,257.000000,11.875000,NaN,NaN,24.000000,2010.0,84.000000,NaN
max,158.000000,168.000000,334.000000,20.700000,NaN,NaN,31.000000,2010.0,97.000000,NaN

In [55]:
weather_data["Weather"].unique()

array(['S', 'C', 'PS', nan], dtype=object)

In [56]:
weather_data["Weather"].value_counts(dropna=False)

Weather
S      59
C      49
PS     47
NaN     3
Name: count, dtype: int64

# Data Pre-processing/ Data preparation

#### Stage - 1 -  Data cleaning - drop,fillna with mean, median, mode imputation, changing dtypes

In [57]:
weather_data.head(7)

   Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0           1   41.0    190.0   7.4     67     5    1  2010    67       S
1           2   36.0    118.0   8.0     72     5    2  2010    72       C
2           3   12.0    149.0  12.6     74     5    3  2010    74      PS
3           4   18.0    313.0  11.5     62     5    4  2010    62       S
4           5    NaN      NaN  14.3     56     5    5  2010    56       S
5           6   28.0      NaN  14.9     66     5    6  2010    66       C
6           7   23.0    299.0   8.6     65     5    7  2010    65      PS

In [58]:
weather_data.drop(["Unnamed: 0","Temp C"],axis=1,inplace=True)

In [59]:
weather_data.head()

   Ozone  Solar.R  Wind Month  Day  Year  Temp Weather
0   41.0    190.0   7.4     5    1  2010    67       S
1   36.0    118.0   8.0     5    2  2010    72       C
2   12.0    149.0  12.6     5    3  2010    74      PS
3   18.0    313.0  11.5     5    4  2010    62       S
4    NaN      NaN  14.3     5    5  2010    56       S

* WE REMOVED THE UNWANTED COLUMS - UNNAMED: 0 , TEMP C -BEACUSE THESE TO COLUMNS DOES NOT CONTRIBUTE TO THE OUTPUT WE NEEDED

In [60]:
weather_data.isna().sum()

Ozone      38
Solar.R     7
Wind        0
Month       0
Day         0
Year        0
Temp        0
Weather     3
dtype: int64

In [61]:
weather_data.shape

(158, 8)

In [62]:
38/158 #almost 25% of data is null

0.24050632911392406

* First i need to talk the client that it has 25% of null values do you have proper dataset / i will ask can i remove this column as it as 25% of null values

In [63]:
del weather_data["Ozone"]

In [64]:
weather_data.head()

   Solar.R  Wind Month  Day  Year  Temp Weather
0    190.0   7.4     5    1  2010    67       S
1    118.0   8.0     5    2  2010    72       C
2    149.0  12.6     5    3  2010    74      PS
3    313.0  11.5     5    4  2010    62       S
4      NaN  14.3     5    5  2010    56       S

In [65]:
weather_data.isna().sum()

Solar.R    7
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    3
dtype: int64

* NOW THERE IS NULL VALUES IN SOLAR.R -HERE WE USE MEAN TI FILL NULL VALUES BECAUSE IT ONLY HAS 7 NULL VALUES SO IT DOES NOT IMPACT THE ORIGINAL DATASET HAS THAT MUCH

In [67]:
weather_data[weather_data["Solar.R"].isna()]

    Solar.R  Wind Month  Day  Year  Temp Weather
4       NaN  14.3     5    5  2010    56       S
5       NaN  14.9     5    6  2010    66       C
10      NaN   6.9     5   11  2010    74       C
26      NaN   8.0     5   27  2010    57      PS
95      NaN   6.9     8    4  2010    86     NaN
96      NaN   7.4     8    5  2010    85       S
97      NaN   4.6     8    6  2010    87       C

In [68]:
weather_data.groupby("Weather")["Solar.R"].mean().round()

Weather
C     192.0
PS    174.0
S     193.0
Name: Solar.R, dtype: float64

In [69]:
weather_data["Solar.R"]= weather_data.groupby("Weather")["Solar.R"].transform(lambda x:x.fillna(x.mean().round()))

In [70]:
weather_data

     Solar.R  Wind Month  Day  Year  Temp Weather
0      190.0   7.4     5    1  2010    67       S
1      118.0   8.0     5    2  2010    72       C
2      149.0  12.6     5    3  2010    74      PS
3      313.0  11.5     5    4  2010    62       S
4      193.0  14.3     5    5  2010    56       S
..       ...   ...   ...  ...   ...   ...     ...
153    190.0   7.4     5    1  2010    67       C
154    193.0   6.9     9   26  2010    70      PS
155    145.0  13.2     9   27  2010    77       S
156    191.0  14.3     9   28  2010    75       S
157    131.0   8.0     9   29  2010    76       C

[158 rows x 7 columns]

In [72]:
weather_data.isna().sum() #still we have 3 null values so need to check

Solar.R    3
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    3
dtype: int64

In [74]:
weather_data[weather_data["Solar.R"].isna()] #here we see there is no value in solar.R and our output also has null values in reality we do not put mean  to our output values if it has null values because it affects in our original dataset

    Solar.R  Wind Month  Day  Year  Temp Weather
87      NaN  12.0     7   27  2010    86     NaN
93      NaN  13.8     8    2  2010    81     NaN
95      NaN   6.9     8    4  2010    86     NaN

In [77]:
weather_data.dropna(inplace=True) #so we drop the null values

In [78]:
weather_data.isna().sum()

Solar.R    0
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    0
dtype: int64

In [79]:
weather_data.shape

(155, 7)

* we are changing the data types

In [81]:
weather_data.dtypes

Solar.R    float64
Wind       float64
Month       object
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [83]:
weather_data["Month"].unique() # here we see every month in number in one row alone there is may so we need to change to the 5 number

array(['5', 'May', '6', '7', '8', '9'], dtype=object)

In [86]:
import warnings
warnings.filterwarnings("ignore")

In [87]:
weather_data["Month"].replace( to_replace="May",value=5,inplace=True)

In [90]:
weather_data["Month"].unique() #we changed it

array(['5', 5, '6', '7', '8', '9'], dtype=object)

In [93]:
weather_data["Month"]= weather_data["Month"].astype("int") #we are changing into to integer

In [94]:
weather_data.dtypes

Solar.R    float64
Wind       float64
Month        int64
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

#### Stage - 2 - Data Transformation
* If data is continuous - Standard scaler, minmaxscaler,Robustscaler
* If data is Discrete - Label encoder, one hot encoder

In [96]:
weather_data_copy_1 = weather_data.copy() #here we are copying out data cleaned dataset into another variable

#### Using Label Encoder

In [97]:
from sklearn.preprocessing import LabelEncoder

In [101]:
le_code =LabelEncoder() # used to change the alphabetical value to numerical values

In [99]:
weather_data_copy_1["Weather"]= le_code.fit_transform(weather_data_copy_1["Weather"])

In [102]:
weather_data_copy_1 #here c= 0, ps = 1, s= 2 because it takes in alphabetical order C is coming first in alphabetical order so C=0, P=1,S=2

     Solar.R  Wind  Month  Day  Year  Temp  Weather
0      190.0   7.4      5    1  2010    67        2
1      118.0   8.0      5    2  2010    72        0
2      149.0  12.6      5    3  2010    74        1
3      313.0  11.5      5    4  2010    62        2
4      193.0  14.3      5    5  2010    56        2
..       ...   ...    ...  ...   ...   ...      ...
153    190.0   7.4      5    1  2010    67        0
154    193.0   6.9      9   26  2010    70        1
155    145.0  13.2      9   27  2010    77        2
156    191.0  14.3      9   28  2010    75        2
157    131.0   8.0      9   29  2010    76        0

[155 rows x 7 columns]

In [104]:
weather_data_copy_1.dtypes # everything we changed into numerical values

Solar.R    float64
Wind       float64
Month        int64
Day          int64
Year         int64
Temp         int64
Weather      int64
dtype: object

#### Using One Hot Encoder 

* This can be achieved using any of the following 2 Libraries

* pandas - pd.get_dummies()

* sklearn - OneHotEncoder()

* USING PANDAS

In [112]:
weather_data_copy_2 = weather_data.copy()

In [113]:
weather_data_copy_2 = pd.get_dummies(data=weather_data_copy_2,columns=["Weather"],dtype="int") #using this it creates a 3 different columns for each output values
weather_data_copy_2

     Solar.R  Wind  Month  Day  Year  Temp  Weather_C  Weather_PS  Weather_S
0      190.0   7.4      5    1  2010    67          0           0          1
1      118.0   8.0      5    2  2010    72          1           0          0
2      149.0  12.6      5    3  2010    74          0           1          0
3      313.0  11.5      5    4  2010    62          0           0          1
4      193.0  14.3      5    5  2010    56          0           0          1
..       ...   ...    ...  ...   ...   ...        ...         ...        ...
153    190.0   7.4      5    1  2010    67          1           0          0
154    193.0   6.9      9   26  2010    70          0           1          0
155    145.0  13.2      9   27  2010    77          0           0          1
156    191.0  14.3      9   28  2010    75          0           0          1
157    131.0   8.0      9   29  2010    76          1           0          0

[155 rows x 9 columns]

* USING ONEHOTENCODER SKLEARN

In [175]:
weather_data_copy_3 = weather_data.copy()

In [176]:
from sklearn.preprocessing import OneHotEncoder

In [177]:
 one_encoder = OneHotEncoder()

In [178]:
one_encoder.fit_transform(weather_data_copy_3[["Weather"]]) #IT returns the compressed sparse row matrix not a regular array this is a default behaviour of the onehotencoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 155 stored elements and shape (155, 3)>

In [179]:
one_encoder=OneHotEncoder(sparse_output=False)

In [180]:
encoded = one_encoder.fit_transform(weather_data_copy_3[["Weather"]])

In [181]:
weather_data_copy_3

     Solar.R  Wind  Month  Day  Year  Temp Weather
0      190.0   7.4      5    1  2010    67       S
1      118.0   8.0      5    2  2010    72       C
2      149.0  12.6      5    3  2010    74      PS
3      313.0  11.5      5    4  2010    62       S
4      193.0  14.3      5    5  2010    56       S
..       ...   ...    ...  ...   ...   ...     ...
153    190.0   7.4      5    1  2010    67       C
154    193.0   6.9      9   26  2010    70      PS
155    145.0  13.2      9   27  2010    77       S
156    191.0  14.3      9   28  2010    75       S
157    131.0   8.0      9   29  2010    76       C

[155 rows x 7 columns]

In [182]:
encoded_df = pd.DataFrame(encoded,columns=one_encoder.get_feature_names_out(["Weather"]))

In [183]:
weather_data_copy_3= pd.concat([weather_data_copy_3.reset_index(drop=True),encoded_df],axis=1)

In [184]:
weather_data_copy_3.head()

,Solar.R,Wind,Month,Day,Year,Temp,Weather,Weather_C,Weather_PS,Weather_S
0,190.0,7.4,5,1,2010,67,S,0.0,0.0,1.0
1,118.0,8.0,5,2,2010,72,C,1.0,0.0,0.0
2,149.0,12.6,5,3,2010,74,PS,0.0,1.0,0.0
3,313.0,11.5,5,4,2010,62,S,0.0,0.0,1.0
4,193.0,14.3,5,5,2010,56,S,0.0,0.0,1.0

In [185]:
weather_data_copy_3  = weather_data_copy_3.drop(columns=["Weather"])

In [186]:
weather_data_copy_3

     Solar.R  Wind  Month  Day  Year  Temp  Weather_C  Weather_PS  Weather_S
0      190.0   7.4      5    1  2010    67        0.0         0.0        1.0
1      118.0   8.0      5    2  2010    72        1.0         0.0        0.0
2      149.0  12.6      5    3  2010    74        0.0         1.0        0.0
3      313.0  11.5      5    4  2010    62        0.0         0.0        1.0
4      193.0  14.3      5    5  2010    56        0.0         0.0        1.0
..       ...   ...    ...  ...   ...   ...        ...         ...        ...
150    190.0   7.4      5    1  2010    67        1.0         0.0        0.0
151    193.0   6.9      9   26  2010    70        0.0         1.0        0.0
152    145.0  13.2      9   27  2010    77        0.0         0.0        1.0
153    191.0  14.3      9   28  2010    75        0.0         0.0        1.0
154    131.0   8.0      9   29  2010    76        1.0         0.0        0.0

[155 rows x 9 columns]

# =================================================================================================================

# HOW TO CHOOSE BTW THE LABEL ENCODER AND ONE HOT ENCODER

* **Input Feature**
* Based on whether it is Parametric or a Non-Parametric Model we will be choosing
* For parametric model we chose - OneHotEncoder
* For Non-Parametric Model we chose - LabelEncoder

* **Output Feature**
* Always the output features must be LabelEncoder